name: SwornGuns
main: net.dmulloy2.swornguns.SwornGuns
version: ${project.version}${project.build.number}
authors: [dmulloy2, Phanta]
description: Guns in Minecraft!
commands: 
  swornguns:
    description: SwornGuns root command
    usage: /<command> <args>
    aliases: [gun, guns]
permissions:
  swornguns.*:
    description: Allows access to all SwornGuns features
    default: false
    children:
      swornguns.toggle: true
      swornguns.reload: true
  swornguns.reload:
    description: Lets you reload the plugin
    default: false
  swornguns.fire:
    description: Per-gun permissions
    default: op
